
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: './app/yarn.lock'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - name: Debug file structure
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo "=== App Directory ==="
          ls -la app/
          echo "=== Check package.json ==="
          cat app/package.json | head -20
      
      - name: Install dependencies
        run: |
          cd app
          yarn install --network-timeout 100000
      
      - name: Create GitHub Pages next.config.js
        run: |
          cd app
          cp next.config.js next.config.js.backup
          cat > next.config.js << 'EOF'
          const path = require('path');
          
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            distDir: process.env.NEXT_DIST_DIR || '.next',
            output: 'export',
            basePath: '/joniwoods-transformation',
            assetPrefix: '/joniwoods-transformation/',
            trailingSlash: true,
            experimental: {
              outputFileTracingRoot: path.join(__dirname, '../'),
            },
            eslint: {
              ignoreDuringBuilds: true,
            },
            typescript: {
              ignoreBuildErrors: false,
            },
            images: { 
              unoptimized: true,
              loader: 'custom',
              loaderFile: './lib/imageLoader.js'
            },
          };
          
          module.exports = nextConfig;
          EOF
      
      - name: Build with Next.js
        run: |
          cd app
          yarn build
          echo "=== Build completed, checking output ==="
          ls -la out/ || echo "No out directory found"
          echo "=== Ensuring all public assets are copied ==="
          cp -r public/* out/ 2>/dev/null || echo "No additional public files to copy"
          echo "=== Final output structure ==="
          find out/ -type f -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.webp" | head -10
      
      - name: Add .nojekyll file
        run: |
          cd app
          touch out/.nojekyll
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
